version: '3'

services:

  fbc-strapi:
    build: 
      context: ./fbc-strapi/
    image: fbc-strapi:latest
    container_name: fbc-strapi
    ports:
      - 1337:1337
    mem_limit: 1g
    cpu_percent: 15
    ulimits: 
      nofile:
        soft: 500000
        hard: 500000
    networks:
      fbc-net:
        ipv4_address: 172.19.0.10

  fbc-frontend:
    depends_on:
      - fbc-strapi
    build:
      context: ./fbc-frontend/
    image: fbc-frontend:latest
    container_name: fbc-frontend
    ports: 
      - 1338:1338
    mem_limit: 250m
    cpu_percent: 10
    networks:
      fbc-net:
        ipv4_address: 172.19.0.11

networks:
  fbc-net:
    name: proxy_net
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/20